import type { Metadata } from "next";
import { Geist } from 'next/font/google'
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { SessionProvider } from "next-auth/react";
import { ThemeProvider } from "next-themes";

const geist = Geist({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
      className={`${geist.className} anti-antialiased w-dvw h-dvh overflow-x-hidden overflow-y-auto dark:bg-[#092635] bg-slate-300`}
      >
      <SessionProvider>
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
        {children}
        </ThemeProvider>
      </SessionProvider>
      <Toaster />
      </body>
    </html>
  );
}
